[project]
name = "bytebox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "docker>=7.1.0",
    "fastapi[standard]>=0.118.0",
    "uvicorn[standard]>=0.33.0",
]
